# Generated by Django 2.2.6 on 2022-03-25 06:31

import DjangoStudent.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='班级')),
                ('headmaster', models.CharField(blank=True, max_length=10, null=True, verbose_name='班主任')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 't_class',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='课程名称')),
                ('score', models.IntegerField(blank=True, verbose_name='学分')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
                'db_table': 't_subjects',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=DjangoStudent.models.Students.get_photo, verbose_name='照片')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=50, verbose_name='性别')),
                ('id_card', models.CharField(max_length=20, verbose_name='身份证号')),
                ('national', models.CharField(max_length=5, verbose_name='民族')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='家庭住址')),
                ('enter_date', models.DateField(verbose_name='入学时间')),
                ('Date_of_birth', models.DateField(verbose_name='出生日期')),
                ('Native_place', models.CharField(max_length=20, verbose_name='籍贯')),
                ('Account_type', models.CharField(max_length=10, verbose_name='户口类型')),
                ('Change_record', models.TextField(blank=True, verbose_name='学籍变更记录')),
                ('specialty', models.TextField(blank=True, verbose_name='特长')),
                ('Disciplinary_records', models.TextField(blank=True, verbose_name='奖惩记录')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoStudent.Class', verbose_name='所在班级')),
                ('subjects', models.ManyToManyField(blank=True, to='DjangoStudent.Subjects', verbose_name='选修课程')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 't_students',
            },
        ),
    ]
