# Generated by Django 2.2.6 on 2022-03-24 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoStudent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.OneToOneField(db_column='username', default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DjangoStudent.Students', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='students',
            name='id_card',
            field=models.CharField(max_length=20, verbose_name='身份证号'),
        ),
    ]
