# Generated by Django 2.2.6 on 2022-03-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoStudent', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=50, verbose_name='性别'),
        ),
    ]
